version: '3.8'

services:
  db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: mssql_container
    ports:
      - "1433:1433"
    environment:
     ACCEPT_EULA: Y
     SA_PASSWORD: YourPassword123!
    networks:
      - datingapp-network
    

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dating-app
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection="Server=db,1433;Database=DatingApp;User Id=sa;Password=YourPassword123!;"
    ports:
     - "8080:8080"
    networks:
      - datingapp-network

networks:
  datingapp-network:
    driver: bridge
