version: '3.8'

services:
  db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: mssql_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123!
    ports:
      - "1433:1433"
    networks:
      - datingapp-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dating-app
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=DatingAppDB;User Id=sa;Password=YourPassword123!
    ports:
     - "80:80"
    networks:
      - datingapp-network

networks:
  datingapp-network:
    driver: bridge
